#pragma once


#define COOLCODE 0x2006

#define COOLCODE_REQUESTGUARDEDREGION CTL_CODE(FILE_DEVICE_UNKNOWN, COOLCODE + 0x80, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define COOLCODE_REQUESTMODULEBASE CTL_CODE(FILE_DEVICE_UNKNOWN, COOLCODE + 0x81, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define COOLCODE_READPHYSICAL CTL_CODE(FILE_DEVICE_UNKNOWN, COOLCODE + 0x82, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define COOLCODE_WRITEPHYSICAL CTL_CODE(FILE_DEVICE_UNKNOWN, COOLCODE + 0x83, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)